#!/usr/bin/env bash

main()
{
    if [[ "$1 $2" == 'stash pop' ]]
    then
        echo "Avoid using 'pop' and instead use 'apply' followed with 'drop'."
        echo "No action taken."
        exit 1
    fi

    if [[ "$1 $2" == 'stash apply' ]]
    then
        # Always try to recreate the index
        command git stash apply --index "${@:3}"
        exit 1
    fi

    command git "$@"
}

main "$@"
